title: Equivariant Grasp
description: Equivariant Grasp is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
code_url: https://github.com/ZXP-S-works/SE2-equivariant-grasp-learning
paper_url: https://openreview.net/forum?id=a3NaSCJ20V
trained_model_url: https://drive.google.com/drive/u/0/folders/1LkS5cjqy69k-FOCAvlagxE1Z9Ff_LyZc
object_meshes_url: https://drive.google.com/drive/u/0/folders/1LkS5cjqy69k-FOCAvlagxE1Z9Ff_LyZc
